// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzvixxwmqkotryqaixop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6dml4eHdtcWtvdHJ5cWFpeG9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDM2MTgsImV4cCI6MjA2MzkxOTYxOH0.RZq7Tq_D7p7s18YKoHK5E3F3r3fL6Da9sVWmzpeFbyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);